/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.6
  Forc version: 0.63.5
  Fuel-Core version: 0.35.0
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;

export type ConditionalReleasePredicateConfigurables = Partial<{
    RECEIVER: AddressInput;
    AMOUNT: BigNumberish;
    SECRET: BigNumberish;
}>;

export type ConditionalReleasePredicateInputs = [receiver: AddressInput, secret: BigNumberish];

export type ConditionalReleasePredicateParameters = Omit<
  PredicateParams<ConditionalReleasePredicateInputs, ConditionalReleasePredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "struct std::address::Address",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "metadataTypeId": 1
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "receiver",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "secret",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "RECEIVER",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "offset": 1224
    },
    {
      "name": "AMOUNT",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 1216
    },
    {
      "name": "SECRET",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 1256
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA5VTTWsTURS9TVMyBaEPMkV5WThCFqOrQK10+YZJmKZJyEM3WTSm3bozqHQ5P0EFPzZCdeXOCURw+X5Cf8IICi0a6EKhpYt43stMMybpogMDd+6959zzzn3DTyv0jChH5smr7lgtsfGYXhFV5K9Tkj/IkrEg52yDOhdxTl7EefQ/Qc1CzUHNmql9Qc1NcO5MbZf/luBe6jwVtNwbkdv1I3e/liPZiDqP64xkEHV2a4yKeF9UqZh+97cpV6zZIXJLD6B038vtAH9P+gOJHom65dbyIXgO+wJx3SbpR5/7VcReWWD2KjA3gLkLzDYwziVG9+nYs0Pko0z+2zQ/2JrmB1vo2+MnRPwnm/XmAw+OtF7HHdmh7pmpP+T+kT6na3qCYQhNq5il8O0mGo5NPJnF0jy8uoOaPuNxvwlsraz4CYOGuRmf9IyyIHpDdPutBZ3Gd3K4f0g8eEm8ERJvxyQfRVZ6Dv59bs83NY/xcJQX0MhM7A9NvOBsJd2P8yyjfsv01vOC/yF6rWefV+g9tLyDpp0zo62Q0WZNtEFXI9YcZPYYDIn/ZRpv8XMnxRcS/No8PqZunfA64HBMDK+sUtNWrF5WPQ85PwKn0QROlnKuJZxZvw4W+OVe5ddzoo0Zv2TGL31PK1fcGZbcCasv9V5X9N3tmNhbn8RVxFMvDxZ4mdWtprrhRwseaK7RJsk2/g8dt79e5ktynVhrk3peRc8S5m75Q4XePdPbMnrCiR7D4aR57Ah676c7UpkdpbqyOxL/6WqKFfzTSv/T8KAgq8Iys0d5hXmOiT1bfQyGTsIvMvxmX9d9/gE2VQ338AQAAA==');

export class ConditionalReleasePredicate extends Predicate<
  ConditionalReleasePredicateInputs,
  ConditionalReleasePredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: ConditionalReleasePredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
