/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.6
  Forc version: 0.63.5
  Fuel-Core version: 0.35.0
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;

export type TimeLockPredicateConfigurables = Partial<{
    RECEIVER: AddressInput;
    DEADLINE: BigNumberish;
}>;

export type TimeLockPredicateInputs = [receiver: AddressInput, current_time: BigNumberish];

export type TimeLockPredicateParameters = Omit<
  PredicateParams<TimeLockPredicateInputs, TimeLockPredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "struct std::address::Address",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "metadataTypeId": 1
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "receiver",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "current_time",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "RECEIVER",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "offset": 1200
    },
    {
      "name": "DEADLINE",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 1192
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA41UTWsTURS9SUcyBaEPMkF5WThCFqOrQK10+YbJME2TkIdusjCmxV9gUOlyfoIKfmyE6irLCURwOT+hP2EEhRYNdKHQ0kU87yXTjEkKDQzcufeec8879034aZVeEOVJ/4xBdxLn2GRCb4gc+euU5A8yZSLIPtukzkWSlxeJgf5nqJmo2aiZC7UB/y2Bz3WeC1rrjcnpepGz7+dJNqLO0zojGUSdJz6jIp5XNSqm7/0dyhd9K0Qu9xBq9t38LvD3pTeU6JGom45vhOA57AvEdYukFw36NcRuRWD2OjA3gbkHzA4w9iVG9anYtULko0z+2zw/3J7nh9vo2+MnRPwnWzz/Jx4cKb22M7ZC1bNQf8S9I3VOR/cEoxCa1jErxrsz03Cs4+kslubh1V3U1BmP+01g/UrMTxg0LM34omZUBNE7ojvvTejUvpPNvUPiwWvijZB4OyH5ODLTc/DvS7u8pXi0h2NDQCPTsTfS8YqzlVU/zrOG+m3dWzcE/0P0Vs0+r9JHaPkATbtnWlsho82caoOuRqI4SO8xGBH/yxTe5Od2ii/M8BvL+IS6dcJjg8PWMbwyy00rZvVK3HOR8yJwak3gZCnnxowz69fBCr+cq/x6SbS54JfM+KXuafWKO8Nmd8LsS7XXG+rudnTslqZxDfHcy4MVXmZ1x3Pd8KMFDxTXeItkG9+HittfL/NlWSLW2qKeW1WzhL5b3ihG757ubWk94VSP5rDTPHYEvQ/SHcWZHaW6sjsS/+lqCir5Vqy+aXhQkDVh6tljI8Y8W8euFX8ORvaMX2T49b6C6Z/TtX7/ANeaDjXQBAAA');

export class TimeLockPredicate extends Predicate<
  TimeLockPredicateInputs,
  TimeLockPredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: TimeLockPredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
