/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.6
  Forc version: 0.63.5
  Fuel-Core version: 0.35.0
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;

export type TimeLockPredicateConfigurables = Partial<{
    RECEIVER: AddressInput;
    AMOUNT: BigNumberish;
    DEADLINE: BigNumberish;
}>;

export type TimeLockPredicateInputs = [receiver: AddressInput, current_time: BigNumberish];

export type TimeLockPredicateParameters = Omit<
  PredicateParams<TimeLockPredicateInputs, TimeLockPredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "struct std::address::Address",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "metadataTypeId": 1
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "receiver",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "current_time",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "RECEIVER",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "offset": 1232
    },
    {
      "name": "AMOUNT",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 1216
    },
    {
      "name": "DEADLINE",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 1224
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA5VTTWsTURS9SUc6BaEPMkF5WThCFqOrQK10OcNkmKZJyEM3WRjT4s6dQaXL+Qkq+LERqqsuJxDB5fsJ/QkjKLRooAuFli7ieS8zzZikCwcGztyPc8879w0/rdFzoiLpx5C9iSywyYReE9XEz1MS38kUiUv22QZ1L5KiuEgM1D9Fzkxz5lzuCXIMORs5Npc75L8EuAvdZy6t9Mfk9PzY2QuKJJpx93GDkQjj7qOAUQnvyzqVsu/BNhVLgRUhVrgPpXtecQf9d4U/FKgRyJtOYETgORi4wA2LhB8fDurAXtXF7DX0XEfPHfRso8e+7FF1CntWhHici3+dxYdbs/hwC3W7/ISI/2Dz3nzk4ZHSaztjK1I1c/kH3D9S53R0TTiKoGkNsyS+nVTDscbTWSyLw6vbyKkzHg9a6A2qkp8waFiY8VnNqLpEb4luvTOhU/tONvcPiIeviDcj4p2ExMPYzM7Bvy3s+Ybi0R6ODRcamcb+SOMlZ6uoepxnBfmburZhuPw30Rs1+7xGH6DlPTTtnGltqzlt5lQbdDUTxUF6j+GI+B+m+k1+bmf9q2n/+mJ/Qr0G4bXBYWsMr8xKy5KsUZV9DzE/BqfWBE6Wca6nnHm/9pf45Vzl1wuijTm/RM4vdU9rV9wZlt4JcyDUXq+pu9vV2CtPcR145uX+Ei/zuuVMN/xowwPFNd4k0cH/oXDny2W8IsrE2pvU92pqlqvvlj+SqN3VtW2tJ5rq0Rx2FseOoPdetiOZ21GmK78j9x9dLbdQDiyp/ml4sCrqLtOzx4bEPFtjz5KfwpGd8rs5fr2v/33+AvCj+GfwBAAA');

export class TimeLockPredicate extends Predicate<
  TimeLockPredicateInputs,
  TimeLockPredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: TimeLockPredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
